Fix backup shell script using kludge.
Look upon this and shutter.

diff --git a/debian/backup b/debian/backup
--- a/debian/backup
+++ b/debian/backup
@@ -1,7 +1,21 @@
 #!/bin/sh
 set -e
 ulimit -s unlimited
-/usr/bin/innobackupex --stream=xbstream \
-    /var/lib/mysql \
-    2>/tmp/xtrabackup.log \
-    | /bin/gzip -
+
+run_backup() {
+    echo "BAD" > /tmp/$$.dumb_hack
+    /usr/bin/innobackupex --stream=xbstream \
+        /var/lib/mysql \
+        2>/tmp/xtrabackup.log
+    echo "0" > /tmp/$$.dumb_hack
+}
+
+
+run_backup | /bin/gzip -
+
+MAGICAL_VAR=`cat /tmp/$$.dumb_hack`
+if [ "0" != "${MAGICAL_VAR}" ]; then
+    echo "Error running xtrabackup!"
+    exit 1
+fi
+
